### ISSUE TITLE
Ray build failures on x86 and PPC

### ISSUE THREAD

**Issue by ArchanaShinde1** [open-ce/open-ce#1041]
```
ERROR: /home/builder/.cache/bazel/_bazel_builder/3e78332a32205418069e4d4ce65c8dff/external/bazel_tools/platforms/BUILD:89:6: in alias rule @bazel_tools//platforms:windows: Constraints from @bazel_tools//platforms have been removed. Please use constraints from @platforms repository embedded in Bazel, or preferably declare dependency on https://github.com/bazelbuild/platforms. See https://github.com/bazelbuild/bazel/issues/8622 for details.
ERROR: /home/builder/.cache/bazel/_bazel_builder/3e78332a32205418069e4d4ce65c8dff/external/bazel_tools/platforms/BUILD:89:6: Analysis of target '@bazel_tools//platforms:windows' failed
ERROR: /home/builder/.cache/bazel/_bazel_builder/3e78332a32205418069e4d4ce65c8dff/external/com_google_protobuf/BUILD.bazel:174:10: While resolving toolchains for target @com_google_protobuf//:protoc: invalid registered toolchain '@bazel_skylib//toolchains/unittest:cmd_toolchain':
```

**Comment by ArchanaShinde1** [comment]
```
INFO: Repository nlohmann_json instantiated at:
  /opt/conda/conda-bld/ray-packages_1709129572249/work/WORKSPACE:6:15: in <toplevel>
  /opt/conda/conda-bld/ray-packages_1709129572249/work/bazel/ray_deps_setup.bzl:329:17: in ray_deps_setup
Repository rule http_archive defined at:
  /home/builder/.cache/bazel/_bazel_builder/b700090ce29c9098040df3174d80f2df/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /home/builder/.cache/bazel/_bazel_builder/b700090ce29c9098040df3174d80f2df/external/com_google_googletest/BUILD.bazel:57:11: errors encountered resolving select() keys for @com_google_googletest//:gtest
ERROR: Analysis of target '//:ray_pkg' failed; build aborted:
```

**Comment by ArchanaShinde1** [comment]
```
bazel-out/k8-opt/bin/src/ray/util/_virtual_includes/util/ray/util/logging.h:225:16: error: ambiguous overload for 'operator<<' (operand types are 'std::ostream' {aka 'std::basic_ostream<char>'} and 'std::nullptr_t')
bazel-out/k8-opt/bin/src/ray/util/_virtual_includes/util/ray/util/logging.h:228:22: error: ambiguous overload for 'operator<<' (operand types are 'std::ostream' {aka 'std::basic_ostream<char>'} and 'std::nullptr_t')
```

**Comment by ArchanaShinde1** [comment]
`FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/conda-bld/ray-packages_1710315025934/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.11/site-packages/ray-2.9.2-py3.11-linux-x86_64.egg/ray/_private/runtime_env/agent/thirdparty_files/aiohttp-3.9.3.dist-info/INSTALLER'
`

**Comment by cdeepali** [comment]
Build failures on x86 are resolved, now need to look into PPC.

**Comment by Archana-Shinde1** [comment]
PPC failures
```
external/boringssl/src/include/openssl/base.h:124:2: error: #error "Unknown target CPU"
  124 | #error "Unknown target CPU"
      |  ^~~~~
[1,624 / 6,278] Compiling src/google/protobuf/compiler/cpp/message.cc [for tool]; 17s processwrapper-sandbox ... (99 actions running)
```

```
+ python -c 'import ray; ray.init(include_dashboard=True)'
2024-04-18 09:50:29,849 INFO worker.py:1715 -- Started a local Ray instance. View the dashboard at ^[[1m^[[32mhttp://127.0.0.1:8265 ^[[39m^[[22m
Traceback (most recent call last):
  File "/home/builder/ray292/open-ce-builder/open_ce/build_feedstock.py", line 167, in build_feedstock_from_command
    conda_build.api.build(os.path.join(os.getcwd(), recipe['path']),
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3102, in build_tree
    test(pkg, config=metadata.config.copy(), stats=stats)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2940, in test
    utils.check_call_env(cmd, env=env, cwd=metadata.config.test_dir, stats=test_stats, rewrite_stdout_env=rewrite_env)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 387, in _func_defaulting_env_to_os_environ
    proc = PopenWrapper(_args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 272, in __init__
    self.out, self.err = self._execute(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 335, in _execute
    self.disk = max(directory_size(disk_usage_dir), self.disk)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 177, in directory_size
    out = subprocess.check_output(command.format(path).split(), stderr=subprocess.PIPE)
  File "/opt/conda/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/conda/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/conda/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/conda/lib/python3.10/subprocess.py", line 1780, in _execute_child
    self.pid = _posixsubprocess.fork_exec(
BlockingIOError: [Errno 11] Resource temporarily unavailable
[OPEN-CE-ERROR]-11 Unable to build recipe: ray-packages-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: ray-packages-feedstock
[Errno 11] Resource temporarily unavailable
ERROR:OPEN-CE:[OPEN-CE-ERROR]-11 Unable to build recipe: ray-packages-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: ray-packages-feedstock
[Errno 11] Resource temporarily unavailable
ERROR OPEN-CE:<module>(139): [OPEN-CE-ERROR]-11 Unable to build recipe: ray-packages-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: ray-packages-feedstock
[Errno 11] Resource temporarily unavailable
export PREFIX=/opt/conda/conda-bld/ray-packages_1713430381733/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place
```
Fixed in https://github.com/open-ce/ray-packages-feedstock/pull/20
