### ISSUE TITLE
[FEEDSTOCK REQUEST] layoutparser

### ISSUE THREAD

**Issue by lehrig** [open-ce/open-ce#1062]
**Describe the package you'd like added**
"layoutparser", a "Unified Toolkit for Deep Learning Based Document Image Analysis" helps parsing documents (e.g., PDFs).

https://github.com/Layout-Parser/layout-parser

**Describe how this package fits in with the project**
In GenAI, documents are often parsed, e.g., in RAG kind of workflows.

**Additional context**
Required by unstructured-inference; see: https://github.com/Unstructured-IO/unstructured-inference/blob/main/requirements/base.in

**Comment by rolweber** [comment]
This looks like a pure Python package that can easily be installed from PyPI.
https://pypi.org/project/layoutparser/#files

**Comment by lehrig** [comment]
Looks like the dependency to `pypdfium2>=4.18.0` cannot be resolved:

```
python3 -m pip install layoutparser
Looking in indexes: https://pypi.org/simple, https://repo.fury.io/mgiessing
Collecting layoutparser
  Downloading layoutparser-0.3.4-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: numpy in /opt/conda/lib/python3.9/site-packages (from layoutparser) (1.23.5)
Collecting opencv-python (from layoutparser)
  Downloading opencv-python-4.9.0.80.tar.gz (92.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.9/92.9 MB 38.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: scipy in /opt/conda/lib/python3.9/site-packages (from layoutparser) (1.10.1)
Requirement already satisfied: pandas in /opt/conda/lib/python3.9/site-packages (from layoutparser) (2.0.3)
Requirement already satisfied: pillow in /opt/conda/lib/python3.9/site-packages (from layoutparser) (9.4.0)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.9/site-packages (from layoutparser) (6.0)
Collecting iopath (from layoutparser)
  Downloading iopath-0.1.10.tar.gz (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.2/42.2 kB 2.2 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pdfplumber (from layoutparser)
  Downloading pdfplumber-0.11.0-py3-none-any.whl.metadata (39 kB)
Collecting pdf2image (from layoutparser)
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.9/site-packages (from iopath->layoutparser) (4.65.0)
Requirement already satisfied: typing_extensions in /opt/conda/lib/python3.9/site-packages (from iopath->layoutparser) (4.7.1)
Requirement already satisfied: portalocker in /opt/conda/lib/python3.9/site-packages (from iopath->layoutparser) (2.8.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.9/site-packages (from pandas->layoutparser) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.9/site-packages (from pandas->layoutparser) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.9/site-packages (from pandas->layoutparser) (2023.3)
Collecting pdfminer.six==20231228 (from pdfplumber->layoutparser)
  Downloading pdfminer.six-20231228-py3-none-any.whl.metadata (4.2 kB)
Collecting pypdfium2>=4.18.0 (from pdfplumber->layoutparser)
  Downloading pypdfium2-4.28.0.tar.gz (140 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.2/140.2 kB 8.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/conda/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-a1kn6qbx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-a1kn6qbx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-a1kn6qbx/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 161, in <module>
        File "<string>", line 152, in main
        File "/tmp/pip-install-41lg8hzf/pypdfium2_e5da38a3db3a4af89651769fa978f2ab/setupsrc/pypdfium2_setup/packaging_base.py", line 610, in parse_pl_spec
          raise RuntimeError(f"No pre-built binaries available for {Host}. You may place custom binaries & bindings in data/sourcebuild and install with `{PlatSpec_EnvVar}=sourcebuild`.")
      RuntimeError: No pre-built binaries available for <Host: linux ppc64le, glibc 2.28>. You may place custom binaries & bindings in data/sourcebuild and install with `PDFIUM_PLATFORM=sourcebuild`.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by rolweber** [comment]
`pypdfium2` is just a Python wrapper for external binaries. The error message in your installation attempt is about those binaries missing. You can get them here for various platforms, but not for ppc64le:
https://github.com/bblanchon/pdfium-binaries/blob/master/README.md

So yes, you should rather request `pypdfium2` and `pypdfium-binaries`.

**Comment by lehrig** [comment]
Closed in favor of https://github.com/open-ce/open-ce/issues/1069
