### ISSUE TITLE
[QUESTION] Error when install "tensorflow-env.yaml"

### ISSUE THREAD

**Issue by superdavidxp** [open-ce/open-ce#176]
Dear All,

I tried to install the "tensorflow-env.yaml" on IBM Power9 but failed, it seems that the listed package is missing. Could someone give me some help here?

Thank you in advance,

///////////////////////////////////////////////////////////////////////////////////////

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Traceback (most recent call last):
  File "/opt/apps/open-ce-v1.0.1/open-ce/open-ce/build_feedstock.py", line 186, in build_feedstock
    config=config, variants=variant)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/build.py", line 3013, in build_tree
    notest=notest,
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/build.py", line 2058, in build
    try_download(m, no_download_source=False, raise_error=True)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/render.py", line 637, in try_download
    source.provide(metadata)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/source.py", line 862, in provide
    timeout=metadata.config.timeout, locking=metadata.config.locking)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/source.py", line 142, in unpack
    src_path, unhashed_fn = download_to_cache(cache_folder, recipe_path, source_dict, verbose)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/source.py", line 98, in download_to_cache
    raise RuntimeError("Could not download %s" % url)
RuntimeError: Could not download http://mirror.centos.org/altarch/7/os/ppc64le/Packages/tzdata-java-2019c-1.el7.noarch.rpm
Failure building recipe: tzdata-java-cos7-ppc64le
Unable to build recipe: cdts-feedstock

**Comment by jayfurmanek** [comment]
Yea, the broke yesterday when CentOS updated a few packages.

https://github.com/open-ce/open-ce/issues/174

We've switched to pull those packages from a more stable directory.
Delete your `cdts-feedstock` directory and run again (it'll pull down the update)

**Comment by superdavidxp** [comment]
Thank you so much for your reply, I have followed your instruction. The installtion runs well until hits the following error. Please guide me for this issue.

////////////////////////
......
TEST END: /opt/apps/open-ce-v1.0.1/condabuild/linux-ppc64le/cudnn-7.6.5_10.2-hd2739c3_1.tar.bz2
Renaming work directory '/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work' to '/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work_moved_cudnn-7.6.5_10.2-hd2739c3_1_linux-ppc64le_main_build_loop'
INFO:conda_build.utils:Renaming work directory '/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work' to '/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work_moved_cudnn-7.6.5_10.2-hd2739c3_1_linux-ppc64le_main_build_loop'
INFO conda_build.utils:shutil_move_more_retrying(2084): Renaming work directory '/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work' to '/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work_moved_cudnn-7.6.5_10.2-hd2739c3_1_linux-ppc64le_main_build_loop'
shutil.move(work)=/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work, dest=/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work_moved_cudnn-7.6.5_10.2-hd2739c3_1_linux-ppc64le_main_build_loop)
INFO:conda_build.utils:shutil.move(work)=/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work, dest=/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work_moved_cudnn-7.6.5_10.2-hd2739c3_1_linux-ppc64le_main_build_loop)
INFO conda_build.utils:shutil_move_more_retrying(2091): shutil.move(work)=/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work, dest=/opt/apps/anaconda3/envs/open-ce/conda-bld/cudnn_1605301424593/work_moved_cudnn-7.6.5_10.2-hd2739c3_1_linux-ppc64le_main_build_loop)
# Automatic uploading is disabled
# If you want to upload package(s) to anaconda.org later, type:

anaconda upload /opt/apps/open-ce-v1.0.1/condabuild/linux-ppc64le/cudnn-7.6.5_10.2-hd2739c3_1.tar.bz2

# To have conda build upload to anaconda.org automatically, use
# $ conda config --set anaconda_upload yes
anaconda_upload is not set.  Not uploading wheels: []
####################################################################################
Resource usage summary:

Total time: 0:06:52.5
CPU usage: sys=0:00:00.0, user=0:00:00.0
Maximum memory usage observed: 4.1M
Total disk usage observed (not including envs): 841.9K
ERROR: local_src_dir path "/opt/apps/open-ce-v1.0.1/tensorrt-feedstock/config/../../local_files" specified doesn't exist
Unable to build recipe: tensorrt-feedstock

**Comment by jayfurmanek** [comment]
Oh, you need to download the TensorRT package separate (the scripts are unable to automate that.

Please see:
https://github.com/open-ce/open-ce#cuda-requirements
and
https://github.com/open-ce/open-ce/blob/master/doc/README.cuda_support.md

**Comment by superdavidxp** [comment]
Thank you for your help, I have put the tar.gz file into local_folder, the installation continued till hit another problem. May I ask for some help here?

/////////////////////////////////

[7,932 / 10,144] Compiling external/org_tensorflow/tensorflow/core/profiler/convert/xplane_to_kernel_stats_db.cc; 143s local ... (160 actions running)
[8,118 / 10,144] Compiling external/org_tensorflow/tensorflow/core/profiler/convert/xplane_to_kernel_stats_db.cc; 239s local ... (160 actions running)
[8,158 / 10,144] Compiling external/org_tensorflow/tensorflow/core/profiler/convert/xplane_to_kernel_stats_db.cc; 364s local ... (160 actions running)
[8,335 / 10,146] Compiling external/org_tensorflow/tensorflow/compiler/xla/service/hlo_evaluator.cc; 416s local ... (158 actions, 156 running)
[8,421 / 10,146] Compiling external/org_tensorflow/tensorflow/compiler/xla/service/hlo_evaluator.cc; 563s local ... (158 actions, 154 running)
[8,457 / 10,146] Compiling external/org_tensorflow/tensorflow/core/kernels/rnn/lstm_ops_gpu.cu.cc; 732s local ... (156 actions, 151 running)

Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/root/.cache/bazel/_bazel_root/4015cc4fb821700d4b63bac1b3f16dea/server/jvm.out')

Traceback (most recent call last):
  File "/opt/apps/open-ce-v1.0.1/open-ce/open-ce/build_feedstock.py", line 186, in build_feedstock
    config=config, variants=variant)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/build.py", line 3013, in build_tree
    notest=notest,
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/build.py", line 2132, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/apps/anaconda3/envs/open-ce/lib/python3.6/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/apps/anaconda3/envs/open-ce/conda-bld/tensorflow-serving_1605581629231/work/conda_build.sh']' returned non-zero exit status 37.
Failure building recipe: tensorflow-serving
Unable to build recipe: tensorflow-serving-feedstock

**Comment by jayfurmanek** [comment]
That often means you are running out of memory. Building TensorFlow is quite resource intensive.
What are the specs of your system? How much memory? Is there anything else running.

Bazel is able to be configured for certain resource usage.  We'd love some input to be able to tune the recipe for appropriate limits.
