### ISSUE TITLE
Open-CE build with CUDA 11 on ppc64le build issue

### ISSUE THREAD

**Issue by ticlazau** [open-ce/open-ce#261]
Hello,

I am trying to compile bare-metal the latest version of OpenCE with CUDA 11.0 and TensorRT-7.2.0.13.CentOS-8.1.ppc64le-gnu.cuda-11.0.cudnn8.0.tar.gz  on IBM AC922 with RHEL8.

I am getting the following error - cannot find -ltcmalloc_minimal:

`Scanning dependencies of target sentencepiece_train-static
[ 37%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/unicode_script.cc.o
[ 38%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/trainer_interface.cc.o
[ 39%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/builder.cc.o
[ 40%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/unigram_model_trainer.cc.o
[ 41%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/word_model_trainer.cc.o
[ 42%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/trainer_factory.cc.o
[ 44%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/bpe_model_trainer.cc.o
[ 44%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/char_model_trainer.cc.o
[ 45%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/pretokenizer_for_training.cc.o
[ 46%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/sentencepiece_trainer.cc.o
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/pretokenizer_for_training.cc: In static member function 'static std::__cxx11::string sentencepiece::pretokenizer::PretokenizerForTrainingInterface::Postprocess(const sentencepiece::SentencePieceText&)':
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/pretokenizer_for_training.cc:49:14: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (prev == piece.begin() && piece.begin() != 0) {
         ~~~~~^~~~~~~~~~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc: In member function 'sentencepiece::util::Status sentencepiece::SentencePieceProcessor::PopulateSentencePieceText(absl::string_view, absl::string_view, const std::vector<long unsigned int>&, const EncodeResult&, sentencepiece::SentencePieceText*) const':
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc:369:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i = 0; i < w.size(); ++i) {
                         ~~^~~~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc:380:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (i == w.size() - 1) {
               ~~^~~~~~~~~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc: In lambda function:
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc:568:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (int j = 0; j < utf8.size(); j++) {
                           ~~^~~~~~~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc:572:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (j == utf8.size() - 1) {
                 ~~^~~~~~~~~~~~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/unigram_model.cc: In member function 'sentencepiece::EncodeResult sentencepiece::unigram::Model::EncodeOptimized(absl::string_view) const':
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/unigram_model.cc:680:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     while (key_pos < size) {
            ~~~~~~~~^~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/unigram_model.cc:701:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (!has_single_node && length == mblen) {
                                 ~~~~~~~^~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc: In member function 'sentencepiece::util::Status sentencepiece::SentencePieceProcessor::PopulateSentencePieceText(absl::string_view, absl::string_view, const std::vector<long unsigned int>&, const EncodeResult&, sentencepiece::SentencePieceText*) const':
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc:369:27: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i = 0; i < w.size(); ++i) {
                         ~~^~~~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc:380:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           if (i == w.size() - 1) {
               ~~^~~~~~~~~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc: In lambda function:
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc:568:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           for (int j = 0; j < utf8.size(); j++) {
                           ~~^~~~~~~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/sentencepiece_processor.cc:572:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             if (j == utf8.size() - 1) {
                 ~~^~~~~~~~~~~~~~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/unigram_model.cc: In member function 'sentencepiece::EncodeResult sentencepiece::unigram::Model::EncodeOptimized(absl::string_view) const':
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/unigram_model.cc:680:20: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     while (key_pos < size) {
            ~~~~~~~~^~~~~~
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/src/unigram_model.cc:701:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (!has_single_node && length == mblen) {
                                 ~~~~~~~^~~~~~~~
[ 47%] Linking CXX shared library libsentencepiece.so
/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/_build_env/bin/../lib/gcc/powerpc64le-conda_cos7-linux-gnu/7.3.0/../../../../powerpc64le-conda_cos7-linux-gnu/bin/ld: cannot find -ltcmalloc_minimal
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/sentencepiece.dir/build.make:312: src/libsentencepiece.so.0.0.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:475: src/CMakeFiles/sentencepiece.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 48%] Linking CXX static library libsentencepiece.a
[ 48%] Built target sentencepiece-static
[ 50%] Linking CXX static library libsentencepiece_train.a
[ 50%] Built target sentencepiece_train-static
make: *** [Makefile:163: all] Error 2
Traceback (most recent call last):
  File "/home/coredump/projects/open-ce/open-ce/build_feedstock.py", line 135, in build_feedstock_from_command
    config=config)
  File "/home/coredump/anaconda3/envs/opence/lib/python3.6/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/home/coredump/anaconda3/envs/opence/lib/python3.6/site-packages/conda_build/build.py", line 3073, in build_tree
    notest=notest,
  File "/home/coredump/anaconda3/envs/opence/lib/python3.6/site-packages/conda_build/build.py", line 2192, in build
    cwd=src_dir, stats=build_stats)
  File "/home/coredump/anaconda3/envs/opence/lib/python3.6/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/coredump/anaconda3/envs/opence/lib/python3.6/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/conda_build.sh']' returned non-zero exit status 2.
[OPEN-CE-ERROR-11] Unable to build recipe: sentencepiece-feedstock
[OPEN-CE-ERROR-11] Unable to build recipe: sentencepiece-feedstock
Command '['/bin/bash', '-o', 'errexit', '/home/coredump/anaconda3/envs/opence/conda-bld/sentencepiece_1610718016205/work/conda_build.sh']' returned non-zero exit status 2.`

Has anyone encountered this issue?

Rgds,
F.M.

**Comment by jayfurmanek** [comment]
We saw this in https://github.com/open-ce/open-ce/issues/36
Basically cmake was finding tcmalloc and trying to enable it if you happened to have it installed locally.
We added a patch (https://github.com/open-ce/torchtext-feedstock/pull/3)  that would force tcmalloc to be disabled, but perhaps it's happening elsewhere as well.

Do you see this fail when building torchtext, or when building sentencepiece itself?

A workaround would be to remove tcmalloc locally if you can temporarily.

**Comment by ticlazau** [comment]
@jayfurmanek @cdeepali 
Thank you!

**Comment by ticlazau** [comment]
I see TRT coded into the YAML file, will be nice to get this a abuild argument

tensorrt-feedstock/tensorrt7.0/tensorrt-graphsurgeon/meta.yaml:{% set trt_tar = "TensorRT-7.0.0.11.CentOS-7.6.ppc64le-gnu.cuda-10.2.cudnn7.6.tar.gz" %} #[ppc64le]
tensorrt-feedstock/tensorrt7.0/tensorrt/meta.yaml:{% set trt_tar = "TensorRT-7.0.0.11.CentOS-7.6.ppc64le-gnu.cuda-10.2.cudnn7.6.tar.gz" %} #[ppc64le]
tensorrt-feedstock/tensorrt7.0/tensorrt-uff/meta.yaml:{% set trt_tar = "TensorRT-7.0.0.11.CentOS-7.6.ppc64le-gnu.cuda-10.2.cudnn7.6.tar.gz" %} #[ppc64le]

**Comment by jayfurmanek** [comment]
For Cuda11, the tensorrt 7.2 package should get built, which needs:
```
{% set trt_tar = "TensorRT-7.2.0.13.CentOS-8.1.ppc64le-gnu.cuda-11.0.cudnn8.0.tar.gz" %} #[ppc64le]
and
{% set trt_tar = "TensorRT-7.2.1.6.CentOS-7.6.x86_64-gnu.cuda-11.0.cudnn8.0.tar.gz" %}  #[x86_64]
```
https://github.com/open-ce/tensorrt-feedstock/blob/master/tensorrt7.2/tensorrt/meta.yaml

make sure to pass in `--cuda_versions 11.0` to the open-ce command line to ensure that get's passed to all the feedstock builds.
