### ISSUE TITLE
Missing conda_build_config arg returns error

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce#310]
**Describe the bug**
An exception is thrown when running `build feedstock` and no `conda_build_config` file is provided or found in the current working directory.

**To Reproduce**
Run `../open-ce/open-ce/open-ce build feedstock` within a feedstock directory.

**Expected behavior**
The build runs successfully.

It might make sense to give a warning saying that no conda_build_config file was found.

**Execution Logs**
```
./open-ce/open-ce/open-ce build feedstock --working_directory itk_repos/antspyx-feedstock/
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Traceback (most recent call last):
  File "/tmp/nemanich/open-ce/open-ce/build_feedstock.py", line 146, in build_feedstock_from_command
    config=config)
  File "/tmp/nemanich/miniconda3/lib/python3.7/site-packages/conda_build/api.py", line 195, in build
    variants=variants
  File "/tmp/nemanich/miniconda3/lib/python3.7/site-packages/conda_build/build.py", line 3050, in build_tree
    bypass_env_check=True)
  File "/tmp/nemanich/miniconda3/lib/python3.7/site-packages/conda_build/render.py", line 857, in render_recipe
    variants = get_package_variants(m, variants=variants)
  File "/tmp/nemanich/miniconda3/lib/python3.7/site-packages/conda_build/variants.py", line 621, in get_package_variants
    combined_spec, specs = get_package_combined_spec(recipedir_or_metadata, config=config, variants=variants)
  File "/tmp/nemanich/miniconda3/lib/python3.7/site-packages/conda_build/variants.py", line 583, in get_package_combined_spec
    specs[f] = parse_config_file(f, config)
  File "/tmp/nemanich/miniconda3/lib/python3.7/site-packages/conda_build/variants.py", line 114, in parse_config_file
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/nemanich/conda_build_config.yaml'
[OPEN-CE-ERROR-11] Unable to build recipe: antspyx-feedstock
[Errno 2] No such file or directory: '/tmp/nemanich/conda_build_config.yaml'
```

**Comment by bethune-bryant** [comment]
After our discussion this morning, I think we should do the following:

* During build feedstock a conda_build_config.yaml file should be optional. I think we should show a warning though that some recipes expect a conda_build_config.yaml to be used.
* During build env we should throw an error if the conda_build_config.yaml can't be located.
  * This could be done by moving this check you have commented out here to build env: https://github.com/npanpaliya/open-ce/blob/bb2d60e8e790b7d7c9bca5894e36da4af22137fb/open_ce/inputs.py#L275..L276
