### ISSUE TITLE
[QUESTION] open-ce 1.3.0 channel for Tensorflow 2.5.0

### ISSUE THREAD

**Issue by Jasperhino** [open-ce/open-ce#481]
I want to use Tensorflow 2.5.0 on a IBM AC922.
Therefore I would want to install `open-ce 1.3.0` from the osu channel using
`conda install -c https://ftp.osuosl.org/pub/open-ce/current/ tensorflow`.

I noticed that https://ftp.osuosl.org/pub/open-ce/current/ is open-ce version `1.1.1`
while https://ftp.osuosl.org/pub/open-ce/ is version `1.2.2`.
However this only provides me with `tensorflow 2.4.1`.
I did not find a channel to use `open-ce 1.3.0`.

I tried create my own channel using the open-ce-builder repository, but the docker build failed. I tried to run
`open-ce build env --build_types cuda --cuda_versions 11.2 --docker_build open-ce/envs/tensorflow-env.yaml`
<details>
<summary>But this gave me the following error... (click to expand)</summary>

```
  open-ce build env --build_types cuda --cuda_versions 11.2 --docker_build open-ce/envs/tensorflow-env.yaml
/usr/bin/podman
STEP 1: FROM nvidia/cuda:11.2.0-devel-ubi8
STEP 2: ENV CONDA_HOME=${CONDA_HOME:-/opt/conda}
--> Using cache f8eda4b742d7bf137f80f1327035acf3dd6bbbf14feec6383ab6b7d64096e3d8
--> f8eda4b742d
STEP 3: ENV PATH=$CONDA_HOME/bin:$PATH
--> Using cache 3fef48ec55f6a161c0445d7817d8702f9e77bb033270303910dc45a036b73059
--> 3fef48ec55f
STEP 4: ENV CUDA_HOME=/usr/local/cuda
--> Using cache e8deeb8eb8619c1c8cf32e1638e5be989fd6c4da8041120ba30147c6d80ee0e5
--> e8deeb8eb86
STEP 5: ENV OPEN_CE_CONDA_BUILD=3.21.4
--> Using cache 2f7e16785eec24838a02b9ca781a9081cada773f994b2af43996139b9a6c2d9f
--> 2f7e16785ee
STEP 6: ENV CICD_GROUP=cicd
--> Using cache e2972eb878f26171422dae6bdcc39e5cdace7a209348f67baccabb5af7796843
--> e2972eb878f
STEP 7: ARG GROUP_ID=1500
--> Using cache 78210422e90a7a59db7b7838d631f8a8d9ae8abd13d0dfca7ec1ff57499059c2
--> 78210422e90
STEP 8: ENV BUILD_USER=builder
--> Using cache 23b789859c332faf2b1ea7a3e7133b4d74a18c2b28d522b5558526197875c6c2
--> 23b789859c3
STEP 9: ARG BUILD_ID=1084
--> Using cache 2c52db5b58879b4334c8c2bbf38257e211117a0ef90ce87e6582fe387dc91e76
--> 2c52db5b588
STEP 10: RUN rpm -e --nodeps --verbose gcc gcc-c++
--> Using cache a9ead8e449f77488e91b9463b54e0cec8d08a19d7ad3644a17f3328ba2841d86
--> a9ead8e449f
STEP 11: RUN export ARCH="$(uname -m)" &&     yum repolist && yum install -y rsync openssh-clients &&     groupadd --non-unique --gid ${GROUP_ID} ${CICD_GROUP} &&     useradd -b /home --non-unique --create-home --gid ${GROUP_ID} --groups wheel     --uid ${BUILD_ID} --comment "User for Building" ${BUILD_USER} &&     curl -o /tmp/anaconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-${ARCH}.sh &&     chmod +x /tmp/anaconda.sh &&     /bin/bash /tmp/anaconda.sh -f -b -p /opt/conda &&     rm -f /tmp/anaconda.sh &&     $CONDA_HOME/bin/conda install -y conda-build=${OPEN_CE_CONDA_BUILD} networkx git junit-xml patch &&     $CONDA_HOME/bin/conda config --system --add envs_dirs $CONDA_HOME/envs &&     $CONDA_HOME/bin/conda config --system --add pkgs_dirs $CONDA_HOME/pkgs &&     $CONDA_HOME/bin/conda config --system --set always_yes true &&     $CONDA_HOME/bin/conda config --system --set auto_update_conda false &&     $CONDA_HOME/bin/conda config --system --set notify_outdated_conda false &&     $CONDA_HOME/bin/conda --version &&     mkdir -p $CONDA_HOME/conda-bld &&     mkdir -p $HOME/.cache &&     echo "export PYTHONPATH=${PYTHONPATH}:$HOME/open_ce" >> ${HOME}/.bashrc &&     chown -R ${BUILD_USER}:${CICD_GROUP} ${CONDA_HOME}
--> Using cache b011fce189c4aa22c356699a3dd32cf59d32f75fe1f3eb38fb2c69e398347067
--> b011fce189c
STEP 12: USER ${BUILD_USER}
--> Using cache 091a862ca122f4a68103a0c7378444640ccb9b2eaa77e99f3cc111a0ed56dd1a
--> 091a862ca12
STEP 13: RUN export PATH="${PATH}" &&     echo "PATH="${PATH}"" >> ${HOME}/.profile &&     mkdir -p $HOME/.cache &&     echo ". $CONDA_HOME/etc/profile.d/conda.sh" >> ${HOME}/.bashrc &&     echo "export PYTHONPATH=${PYTHONPATH}:$HOME/open_ce" >> ${HOME}/.bashrc &&     echo "conda activate base" >> ${HOME}/.bashrc
--> Using cache a4c24655a300317d34e64aaa6f74a099af27a837b6fad8f51391ebef96476374
STEP 14: COMMIT open-ce:open-ce-builder-cuda11.2
--> a4c24655a30
a4c24655a300317d34e64aaa6f74a099af27a837b6fad8f51391ebef96476374
e0915df6714624bc6f37973d6b77938e1ab9f5681aac79766125db6eb9c7242f
open-ce-builder-20210811093009
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/cdts-feedstock.git cdts-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/cudnn-feedstock.git cudnn-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/nccl-feedstock.git nccl-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/bazel-feedstock.git bazel-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/cudatoolkit-feedstock.git cudatoolkit-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorflow-feedstock.git tensorflow-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/dm-tree-feedstock.git dm-tree-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorflow-probability-feedstock.git tensorflow-probability-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorflow-estimator-feedstock.git tensorflow-estimator-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorboard-data-server-feedstock.git tensorboard-data-server-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorboard-feedstock.git tensorboard-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorflow-text-feedstock.git tensorflow-text-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorflow-hub-feedstock.git tensorflow-hub-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorflow-model-optimization-feedstock.git tensorflow-model-optimization-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorflow-metadata-feedstock.git tensorflow-metadata-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorflow-datasets-feedstock.git tensorflow-datasets-feedstock
Cloning into 'tensorflow-text-feedstock'...
Cloning into 'tensorboard-data-server-feedstock'...
Cloning into 'cudatoolkit-feedstock'...
Cloning into 'tensorboard-feedstock'...
Cloning into 'tensorflow-probability-feedstock'...
Cloning into 'bazel-feedstock'...
Cloning into 'dm-tree-feedstock'...
Cloning into 'nccl-feedstock'...
Cloning into 'cudnn-feedstock'...
Cloning into 'tensorflow-feedstock'...
Cloning into 'tensorflow-datasets-feedstock'...
Cloning into 'tensorflow-metadata-feedstock'...
Cloning into 'tensorflow-estimator-feedstock'...
Cloning into 'tensorflow-hub-feedstock'...
Cloning into 'tensorflow-model-optimization-feedstock'...
Cloning into 'cdts-feedstock'...
/opt/conda/lib/python3.9/site-packages/conda_build/environ.py:447: UserWarning: The environment variable 'CUDA_HOME' is being passed through with value '/usr/local/cuda'.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
  warnings.warn(
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/typeguard-feedstock.git typeguard-feedstock
INFO:OPEN-CE:Clone cmd: git clone https://github.com/open-ce/typeguard-feedstock.git typeguard-feedstock
[OPEN-CE-INFO]Clone cmd: git clone https://github.com/open-ce/tensorflow-addons-feedstock.git tensorflow-addons-feedstock
INFO:OPEN-CE:Clone cmd: git clone https://github.com/open-ce/tensorflow-addons-feedstock.git tensorflow-addons-feedstock
Cloning into 'typeguard-feedstock'...
Cloning into 'tensorflow-addons-feedstock'...
/opt/conda/lib/python3.9/site-packages/conda_build/environ.py:441: UserWarning: The environment variable 'NVTOOLSEXT_INSTALL_PATH' is undefined.
  warnings.warn(
/opt/conda/lib/python3.9/site-packages/conda_build/environ.py:441: UserWarning: The environment variable 'DEBUG_INSTALLER_PATH' is undefined.
  warnings.warn(
/opt/conda/lib/python3.9/site-packages/conda_build/environ.py:447: UserWarning: The environment variable 'CUDA_HOME' is being passed through with value '/usr/local/cuda'.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
  warnings.warn(
/opt/conda/lib/python3.9/site-packages/conda_build/environ.py:447: UserWarning: The environment variable 'CUDA_HOME' is being passed through with value '/usr/local/cuda'.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
  warnings.warn(
[OPEN-CE-INFO]Generated conda environment files from the selected build arguments: dict_values(['/root/condabuild/opence-conda-env-py3.8-cuda-openmpi-11.2.yaml'])
[OPEN-CE-INFO]One can use these environment files to create a conda environment using "conda env create -f <conda_env_file_name>."
[OPEN-CE-INFO]Building cudatoolkit-feedstock
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.16
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /root/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /root/conda_build_config.yaml
Adding in variants from /root/cudatoolkit-feedstock/recipe/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /root/cudatoolkit-feedstock/recipe/conda_build_config.yaml
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
/opt/conda/lib/python3.9/site-packages/conda_build/environ.py:441: UserWarning: The environment variable 'NVTOOLSEXT_INSTALL_PATH' is undefined.
  warnings.warn(
/opt/conda/lib/python3.9/site-packages/conda_build/environ.py:441: UserWarning: The environment variable 'DEBUG_INSTALLER_PATH' is undefined.
  warnings.warn(
Attempting to finalize metadata for cudatoolkit
INFO:conda_build.metadata:Attempting to finalize metadata for cudatoolkit
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['cudatoolkit-11.2.2-h40e65fe_8.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/cudatoolkit_1628667021178/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p


The following NEW packages will be INSTALLED:

    _libgcc_mutex: 0.1-main         
    _openmp_mutex: 4.5-1_gnu        
    libgcc-ng:     9.3.0-h5101ec6_17
    libgomp:       9.3.0-h5101ec6_17
    libstdcxx-ng:  9.3.0-hd4cf53a_17

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /opt/conda/conda-bld/cudatoolkit_1628667021178/_build_env


The following NEW packages will be INSTALLED:

    _libgcc_mutex:                        0.1-main                
    _openmp_mutex:                        4.5-1_gnu               
    _sysroot_linux-64_curr_repodata_hack: 3-haa98f57_10           
    binutils_impl_linux-64:               2.28.1-had2808c_3       
    binutils_linux-64:                    7.2.0-had2808c_27       
    ca-certificates:                      2021.7.5-h06a4308_1     
    certifi:                              2021.5.30-py39h06a4308_0
    gcc_impl_linux-64:                    7.2.0-habb00fd_3        
    gcc_linux-64:                         7.2.0-h550dcbe_27       
    gxx_impl_linux-64:                    7.2.0-hdf63c60_3        
    gxx_linux-64:                         7.2.0-h550dcbe_27       
    kernel-headers_linux-64:              3.10.0-h57e8cba_10      
    ld_impl_linux-64:                     2.33.1-h53a641e_7       
    libffi:                               3.3-he6710b0_2          
    libgcc-ng:                            9.3.0-h5101ec6_17       
    libgomp:                              9.3.0-h5101ec6_17       
    libstdcxx-ng:                         9.3.0-hd4cf53a_17       
    ncurses:                              6.2-he6710b0_1          
    openssl:                              1.1.1k-h27cfd23_0       
    pip:                                  21.2.2-py39h06a4308_0   
    python:                               3.9.6-h12debd9_0        
    readline:                             8.1-h27cfd23_0          
    setuptools:                           52.0.0-py39h06a4308_0   
    sqlite:                               3.36.0-hc218d9a_0       
    sysroot_linux-64:                     2.17-h57e8cba_10        
    tk:                                   8.6.10-hbc83047_0       
    tzdata:                               2021a-h52ac0ba_0        
    wheel:                                0.36.2-pyhd3eb1b0_0     
    xz:                                   5.2.5-h7b6447c_0        
    zlib:                                 1.2.11-h7b6447c_3       

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Copying /root/cudatoolkit-feedstock/recipe/build.py to /opt/conda/conda-bld/cudatoolkit_1628667021178/work/
Source cache directory is: /opt/conda/conda-bld/src_cache
INFO:conda_build.source:Source cache directory is: /opt/conda/conda-bld/src_cache
INFO conda_build.source:download_to_cache(44): Source cache directory is: /opt/conda/conda-bld/src_cache
Downloading source to cache: cuda_11.2.2_460.32.03_linux_955ae5d595.run
INFO:conda_build.source:Downloading source to cache: cuda_11.2.2_460.32.03_linux_955ae5d595.run
INFO conda_build.source:download_to_cache(69): Downloading source to cache: cuda_11.2.2_460.32.03_linux_955ae5d595.run
Downloading https://developer.download.nvidia.com/compute/cuda/11.2.2/local_installers/cuda_11.2.2_460.32.03_linux.run
INFO:conda_build.source:Downloading https://developer.download.nvidia.com/compute/cuda/11.2.2/local_installers/cuda_11.2.2_460.32.03_linux.run
INFO conda_build.source:download_to_cache(83): Downloading https://developer.download.nvidia.com/compute/cuda/11.2.2/local_installers/cuda_11.2.2_460.32.03_linux.run
Success
INFO:conda_build.source:Success
INFO conda_build.source:download_to_cache(94): Success
/opt/conda/conda-bld/cudatoolkit_1628667021178/_build_env/etc/conda/activate.d/activate-binutils_linux-64.sh: line 113: diff: command not found
/opt/conda/conda-bld/cudatoolkit_1628667021178/_build_env/etc/conda/activate.d/activate-gcc_linux-64.sh: line 154: diff: command not found
/opt/conda/conda-bld/cudatoolkit_1628667021178/_build_env/etc/conda/activate.d/activate-gxx_linux-64.sh: line 118: diff: command not found
/opt/conda/conda-bld/cudatoolkit_1628667021178/work/cuda_11.2.2_460.32.03_linux.run: line 215: /dev/tty: No such device or address
/opt/conda/conda-bld/cudatoolkit_1628667021178/work/cuda_11.2.2_460.32.03_linux.run: line 215: /dev/tty: No such device or address
Signal caught, cleaning up
Traceback (most recent call last):
  File "/opt/conda/conda-bld/cudatoolkit_1628667021178/work/build.py", line 463, in <module>
    main()
  File "/opt/conda/conda-bld/cudatoolkit_1628667021178/work/build.py", line 459, in main
    extractor.extract()
  File "/opt/conda/conda-bld/cudatoolkit_1628667021178/work/build.py", line 415, in extract
    self.run_extract(cmd, check=check)
  File "/opt/conda/conda-bld/cudatoolkit_1628667021178/work/build.py", line 350, in run_extract
    caller(cmd)
  File "/opt/conda/conda-bld/cudatoolkit_1628667021178/_build_env/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/conda/conda-bld/cudatoolkit_1628667021178/work/cuda_11.2.2_460.32.03_linux.run', '--silent', '--override', '--nox11', '--toolkit', '--installpath=/tmp/tmpr4c5me8i']' returned non-zero exit status 15.
Traceback (most recent call last):
  File "/root/open_ce/build_feedstock.py", line 150, in build_feedstock_from_command
    conda_build.api.build(os.path.join(os.getcwd(), recipe['path']),
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2191, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/cudatoolkit_1628667021178/work/conda_build.sh']' returned non-zero exit status 1.
[OPEN-CE-ERROR]-11 Unable to build recipe: cudatoolkit-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: cudatoolkit-feedstock
Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/cudatoolkit_1628667021178/work/conda_build.sh']' returned non-zero exit status 1.
ERROR:OPEN-CE:[OPEN-CE-ERROR]-11 Unable to build recipe: cudatoolkit-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: cudatoolkit-feedstock
Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/cudatoolkit_1628667021178/work/conda_build.sh']' returned non-zero exit status 1.
ERROR OPEN-CE:<module>(139): [OPEN-CE-ERROR]-11 Unable to build recipe: cudatoolkit-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: cudatoolkit-feedstock
Command '['/bin/bash', '-o', 'errexit', '/opt/conda/conda-bld/cudatoolkit_1628667021178/work/conda_build.sh']' returned non-zero exit status 1.
Extracting download
Warning: Unrecognized source format. Source file will be copied to the SRC_DIR
source tree in: /opt/conda/conda-bld/cudatoolkit_1628667021178/work
export PREFIX=/opt/conda/conda-bld/cudatoolkit_1628667021178/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p
export BUILD_PREFIX=/opt/conda/conda-bld/cudatoolkit_1628667021178/_build_env
export SRC_DIR=/opt/conda/conda-bld/cudatoolkit_1628667021178/work
INFO: activate-binutils_linux-64.sh made the following environmental changes:
INFO: activate-gcc_linux-64.sh made the following environmental changes:
INFO: activate-gxx_linux-64.sh made the following environmental changes:
11.2.2
Running build
Extract command: $SRC_DIR/cuda_11.2.2_460.32.03_linux.run --silent --override --nox11 --toolkit --installpath=/tmp/tmpr4c5me8i
No log file found
e0915df6714624bc6f37973d6b77938e1ab9f5681aac79766125db6eb9c7242f
[OPEN-CE-ERROR]-4 Error executing build in container: "open-ce-builder-20210811093009"
```
</details>

Do I need to run this on a linux-ppc64le system to create a channel I can use on a ppc64le machine?
When do new open-ce versions get published on the osu channel (especially `open-ce 1.3.0`)?
Are there other channels that provide `open-ce 1.3.0`?

**Comment by npanpaliya** [comment]
At present there is no channel where open-ce 1.3 packages are published which is accessible to external users. 

Do I need to run this on a linux-ppc64le system to create a channel I can use on a ppc64le machine?
--> Yes, you would need to run this on a linux-ppc64le system so that the packages are generated for that architecture and you can use them on ppc64le machine.

For the build error - could you please mention more details about the host system and podman version?

**Comment by Jasperhino** [comment]
> Yes, you would need to run this on a linux-ppc64le system so that the packages are generated for that architecture and you can use them on ppc64le machine.

Ah that probably explains my build error then. Unfortunately, I can not run docker or podman on my ppc64le machine due to security restrictions.
But am I on the right track with my approach of using the open-ce-builder for building a package with Tensorflow 2.5.0, that I can use on my ppc64le machine?
Then I would try to build it again, bare-metal without `--docker_build`...

> At present there is no channel where open-ce 1.3 packages are published which is accessible to external users.

When do new open-ce versions get published on the osu channel (especially open-ce 1.3.0)?

**Comment by npanpaliya** [comment]
Yes, please try building it again on baremetal without --docker_build option. For now, I would also suggest you to use main branches of open-ce and tensorflow-feedstock.
Regarding publishing of 1.3.0 versions on osu channel, @jayfurmanek may know when it will be done.

**Comment by alexlang74** [comment]
https://ftp.osuosl.org/pub/open-ce/  contains the latest OpenCE libraries, including up to 1.5.1. Closing this issue
