### ISSUE TITLE
[BUG] Failed compiling TensorFlow within Open-CE 1.4.0

### ISSUE THREAD

**Issue by ticlazau** [open-ce/open-ce#523]
Hello,

I have the same system I have compiled previous open-ce versions, with the new version I have the following issue:

**ERROR: /home/florin/.cache/bazel/_bazel_florin/7c5d6d170c6651990ae163b9f37636bc/external/rules_cuda/cuda/BUILD:128:20: every rule of type cuda_toolchain_info implicitly depends upon the target '@local_cuda//:cuda/bin/nvcc', but this target could not be found because of: no such target '@local_cuda//:cuda/bin/nvcc': target 'cuda/bin/nvcc' not declared in package '' (did you mean 'cuda/bin/h5cc'?) defined by /home/florin/.cache/bazel/_bazel_florin/7c5d6d170c6651990ae163b9f37636bc/external/local_cuda/BUILD**

I can call nvcc from CLI:
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Thu_Oct_24_17:58:26_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

Details:

```
#Clean up old bazel cache to avoid problems building TF
bazel clean --expunge
+ bazel clean --expunge
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=180
INFO: Reading rc options for 'clean' from /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'clean' from /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Found applicable config definition build:short_logs in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:linux in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false
INFO: Found applicable config definition build:dynamic_kernels in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
bazel shutdown
+ bazel shutdown

bazel --bazelrc=$SRC_DIR/tensorflow/tensorflow.bazelrc build \
    --local_cpu_resources=HOST_CPUS*0.50 \
    --local_ram_resources=HOST_RAM*0.50 \
    --jobs=HOST_CPUS*0.5 \
    --config=opt \
    --config=numa \
    --curses=no \
    //tensorflow/tools/pip_package:build_pip_package
+ bazel --bazelrc=/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/tensorflow.bazelrc build '--local_cpu_resources=HOST_CPUS*0.50' '--local_ram_resources=HOST_RAM*0.50' '--jobs=HOST_CPUS*0.5' --config=opt --config=numa --curses=no //tensorflow/tools/pip_package:build_pip_package
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=180
INFO: Reading rc options for 'build' from /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/nvidia_components_configure.bazelrc:
  'build' options: --config=cuda --action_env TF_CUDA_VERSION=10 --action_env TF_CUDNN_VERSION=8 --action_env TF_NCCL_VERSION=2 --action_env TF_CUDA_PATHS=/usr/local/cuda-10.2/,/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla,/usr/include --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-10.2/,/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla,/usr/include --action_env TF_CUDA_COMPUTE_CAPABILITIES=sm_37,sm_60,sm_70,sm_75,compute_75 --action_env GCC_HOST_COMPILER_PATH=/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/_build_env/bin/powerpc64le-conda_cos7-linux-gnu-cc
INFO: Reading rc options for 'build' from /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/python_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python --action_env PYTHON_LIB_PATH=/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.7/site-packages --python_path=/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
INFO: Reading rc options for 'build' from /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/tensorflow.bazelrc:
  'build' options: --config=xla --action_env TF_CONFIGURE_IOS=0 --action_env TF_SYSTEM_LIBS=org_sqlite --define=PREFIX=/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla --define=LIBDIR=/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib --define=INCLUDEDIR=/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/include --strip=always --color=yes --verbose_failures --spawn_strategy=standalone
INFO: Found applicable config definition build:short_logs in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:cuda in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --repo_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda
INFO: Found applicable config definition build:xla in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --define=with_xla_supprt=true
INFO: Found applicable config definition build:xla in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/tensorflow.bazelrc: --define with_xla_support=true
INFO: Found applicable config definition build:opt in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/tensorflow.bazelrc: --copt=-mcpu=power8 --host_copt=-mcpu=power8 --copt=-mtune=power9 --host_copt=-mtune=power9 --copt=-mvsx --define with_default_optimizations=true
INFO: Found applicable config definition build:numa in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --define=with_numa_support=true
INFO: Found applicable config definition build:linux in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false
INFO: Found applicable config definition build:dynamic_kernels in file /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
DEBUG: /home/florin/.cache/bazel/_bazel_florin/7c5d6d170c6651990ae163b9f37636bc/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.
DEBUG: /home/florin/.cache/bazel/_bazel_florin/7c5d6d170c6651990ae163b9f37636bc/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:10:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
Loading:  (1 packages loaded)
Loading: 1 packages loaded
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (2 packages loaded, 0 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (60 packages loaded, 14 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (223 packages loaded, 3943 targets configured)
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1556410077 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/WORKSPACE:23:14: in <toplevel>
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/workspace0.bzl:108:34: in workspace
  /home/florin/.cache/bazel/_bazel_florin/7c5d6d170c6651990ae163b9f37636bc/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories
Repository rule git_repository defined at:
  /home/florin/.cache/bazel/_bazel_florin/7c5d6d170c6651990ae163b9f37636bc/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (228 packages loaded, 3943 targets configured)
Analyzing: target //tensorflow/tools/pip_package:build_pip_package (253 packages loaded, 3985 targets configured)
ERROR: /home/florin/.cache/bazel/_bazel_florin/7c5d6d170c6651990ae163b9f37636bc/external/rules_cuda/cuda/BUILD:128:20: every rule of type cuda_toolchain_info implicitly depends upon the target '@local_cuda//:cuda/bin/nvcc', but this target could not be found because of: no such target '@local_cuda//:cuda/bin/nvcc': target 'cuda/bin/nvcc' not declared in package '' (did you mean 'cuda/bin/h5cc'?) defined by /home/florin/.cache/bazel/_bazel_florin/7c5d6d170c6651990ae163b9f37636bc/external/local_cuda/BUILD
INFO: Repository icu instantiated at:
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/WORKSPACE:15:14: in <toplevel>
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/workspace2.bzl:1091:28: in workspace
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/workspace2.bzl:68:8: in _initialize_third_party
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/third_party/icu/workspace.bzl:6:20: in repo
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/third_party/repo.bzl:66:35: in <toplevel>
INFO: Repository 'icu' used the following cache hits instead of downloading the corresponding file.
 * Hash 'dfc62618aa4bd3ca14a3df548cd65fe393155edd213e49c39f3a30ccd618fc27' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/unicode-org/icu/archive/release-64-2.zip
If the definition of 'icu' was updated, verify that the hashes were also updated.
INFO: Repository cudnn_frontend_archive instantiated at:
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/WORKSPACE:15:14: in <toplevel>
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/workspace2.bzl:1098:21: in workspace
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/tensorflow/workspace2.bzl:158:20: in _tf_repositories
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  /home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/third_party/repo.bzl:66:35: in <toplevel>
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted: Analysis failed
INFO: Elapsed time: 12.801s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (411 packages loaded, 11617 targets configured)
FAILED: Build did NOT complete successfully (411 packages loaded, 11617 targets configured)
Traceback (most recent call last):
  File "/home/florin/projects/open-ce-builder/open_ce/build_feedstock.py", line 166, in build_feedstock_from_command
    conda_build.api.build(os.path.join(os.getcwd(), recipe['path']),
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/build.py", line 3085, in build_tree
    packages_from_this = build(metadata, stats,
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/build.py", line 2368, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/build.py", line 1613, in bundle_conda
    utils.check_call_env(interpreter_and_args + [dest_file],
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/utils.py", line 412, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/home/florin/anaconda3/envs/opence/lib/python3.8/site-packages/conda_build/utils.py", line 392, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/usr/bin/bash', '-e', '/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/build-pip-package.sh']' returned non-zero exit status 1.
[OPEN-CE-ERROR]-11 Unable to build recipe: tensorflow-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: tensorflow-base
Command '['/usr/bin/bash', '-e', '/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/build-pip-package.sh']' returned non-zero exit status 1.
ERROR:OPEN-CE:[OPEN-CE-ERROR]-11 Unable to build recipe: tensorflow-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: tensorflow-base
Command '['/usr/bin/bash', '-e', '/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/build-pip-package.sh']' returned non-zero exit status 1.
ERROR OPEN-CE:<module>(139): [OPEN-CE-ERROR]-11 Unable to build recipe: tensorflow-feedstock
[OPEN-CE-ERROR]-11 Unable to build recipe: tensorflow-base
Command '['/usr/bin/bash', '-e', '/home/florin/anaconda3/envs/opence/conda-bld/tensorflow-base_1632565320104/work/build-pip-package.sh']' returned non-zero exit status 1.
```

Any advise?
Rgds,
FM

**Comment by npanpaliya** [comment]
@ticlazau - Hope you've CUDA_HOME environment variable set properly.

**Comment by ticlazau** [comment]
@npanpaliya I do have:

```
export CUDA_HOME=/usr/local/cuda-10.2/
export PATH=/usr/local/cuda-10.2/bin${PATH:+:${PATH}}
```

**Comment by npanpaliya** [comment]
I'll request you to try cleaning bazel cache from your home directory ~/.cache/bazel. Also, please share the build command that you have used.

**Comment by ticlazau** [comment]
@npanpaliya let me try cleaning the cache, I did't done this from the last build. thx

**Comment by npanpaliya** [comment]
> @npanpaliya let me try cleaning the cache, I did't done this from the last build. thx

Great! Please let me know how it goes and if you again hit any error.

**Comment by ticlazau** [comment]
@npanpaliya I have the same error :(
Here is my build command: open-ce build env --build_types cuda --cuda_versions 10.2 --output_folder /data/html --python_versions 3.7,3.8,3.9 /home/florin/projects/open-ce/envs/opence-env.yaml

**Comment by ticlazau** [comment]
Thank you @npanpaliya, issue was caused by the disk available space on the system.
