### ISSUE TITLE
feedstock test failure

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce#977]
feedstock test fails with:

Traceback (most recent call last):
  File "/home/runner/work/bazel-feedstock/bazel-feedstock/open-ce-builder/tests/feedstock_tests/check_build_numbers.py", line 27, in <module>
    from common import get_configs, make_parser, get_build_numbers
  File "/home/runner/work/bazel-feedstock/bazel-feedstock/open-ce-builder/tests/feedstock_tests/common.py", line 24, in <module>
    import conda_build.api
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/conda_build/api.py", line 22, in <module>
    from conda_build.config import (Config, get_or_merge_config, get_channel_urls,
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/conda_build/config.py", line 15, in <module>
    from .conda_interface import root_dir, root_writable
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/conda_build/conda_interface.py", line 119, in <module>
    context_get_prefix = try_exports("conda.base.context", "get_prefix")
  File "/usr/share/miniconda/envs/test/lib/python3.10/site-packages/conda_build/conda_interface.py", line 16, in try_exports
    return getattr(import_module(module), attr)
AttributeError: module 'conda.base.context' has no attribute 'get_prefix'
Error: Process completed with exit code 1.

https://github.com/open-ce/bazel-feedstock/actions/runs/7445988477/job/20255350242?pr=37

**Comment by cdeepali** [comment]
This is resolved.
